引入mapstruct，用于entity和dto的映射
qms-dev/qmoj-core pull request #5
Opened 2020-12-20 10:06 UTC by GadHao

2020-12-20 13:40 UTC, timeaftertime requested changes

2020-12-20 13:40 UTC, timeaftertime commented on qmoj/src/main/java/team/akina/qmoj/constants/Enums.java
> +public class Enums {
一般是每个枚举一个类，可以都放在一个包里，而不是所有类放在一个 Enums 类里

2020-12-20 13:40 UTC, timeaftertime commented on qmoj/src/main/java/team/akina/qmoj/dto/QmojQuestionDto.java
> +public class QmojQuestionDto {
DTO

2020-12-20 13:40 UTC, timeaftertime commented on qmoj/src/main/java/team/akina/qmoj/dto/QmojQuestionDto.java
> +    private List<String> topic_tags;
应该用驼峰命名

2020-12-20 13:40 UTC, timeaftertime commented on qmoj/src/main/java/team/akina/qmoj/dto/QmojQuestionDto.java
> +    public long getId() {
可以直接用 Lombok 的 @Data 注解

2020-12-20 13:40 UTC, timeaftertime commented on qmoj/src/main/java/team/akina/qmoj/dto/QmojQuestionDto.java
> +    public List<String> getTopic_tags() {
同驼峰

2020-12-20 13:40 UTC, timeaftertime commented on qmoj/src/main/java/team/akina/qmoj/dto/mapper/QmojQuestionDtoMapper.java
> +    @Mappings({@Mapping(target = "platform", expression = "java(platFormConvert(question.getPlatform()))"),
尽量不要写 expression ，这样不方便维护
这种简单的 platform 到 getPlatform 应该是可以直接映射的

2020-12-20 13:40 UTC, timeaftertime commented on qmoj/src/main/java/team/akina/qmoj/dto/mapper/QmojQuestionDtoMapper.java
> +    default String platFormConvert(byte code) {
这应该是 Platform 这个枚举的逻辑，根据职责划分应该放在 Platform 枚举里

2020-12-20 13:40 UTC, timeaftertime commented on qmoj/src/main/java/team/akina/qmoj/dto/mapper/QmojQuestionDtoMapper.java
> +    default List<Integer> languagesConvert(String languages) {
应该用 static 而不是 default

2020-12-20 13:40 UTC, timeaftertime commented on qmoj/src/main/java/team/akina/qmoj/dto/mapper/QmojQuestionDtoMapper.java
> +    default List<String> tagsConvert(String tags) {
同上

2020-12-20 13:40 UTC, timeaftertime commented on qmoj/src/main/java/team/akina/qmoj/exception/DataNotFindException.java
> +public class DataNotFindException extends CustomException {
CustomException  是谁取的名字……吊起来打……

2020-12-20 13:40 UTC, timeaftertime commented on qmoj/src/main/java/team/akina/qmoj/exception/ExceptionHelper.java
> +        logger.error(Arrays.toString(ex.getStackTrace()));
确定这种方式能打印完整、易读的堆栈信息吗

2020-12-20 13:40 UTC, timeaftertime commented on qmoj/src/main/java/team/akina/qmoj/exception/ExceptionHelper.java
> +    @ExceptionHandler(value = {DataNotFindException.class})
全局异常处理器放在这个位置是不是不太合适，而且确定这样能生效吗，能被 Spring 管理吗

2020-12-20 13:40 UTC, timeaftertime commented on qmoj/src/test/java/team/akina/qmoj/dto/DtoConvertTest.java
> +public class DtoConvertTest {
同 DTO

2020-12-20 13:40 UTC, timeaftertime commented on qmoj/src/test/java/team/akina/qmoj/dto/DtoConvertTest.java
> +    public Date getCurrentTime() {
获取时间的方式似乎有点复杂了，一般是 Date 加 SimpleDateFormatter

2020-12-20 13:59 UTC, GadHao commented on qmoj/src/main/java/team/akina/qmoj/constants/Enums.java
> +public class Enums {
因为想到这样可能会产生很多文件，在C#里经常喜欢这样写，我改改

2020-12-20 14:03 UTC, GadHao commented on qmoj/src/main/java/team/akina/qmoj/dto/QmojQuestionDto.java
> +public class QmojQuestionDto {
这边按照[mapstruct的官方示例](https://mapstruct.org/)写的，写的时候也犹豫了一下，这边统一改成大写的吧，在语义上正确些

2020-12-20 14:11 UTC, GadHao commented on qmoj/src/main/java/team/akina/qmoj/dto/QmojQuestionDto.java
> +    private List<String> topic_tags;
这里中邪了，用成python的命名方式了，下次部署的时候让前端同步

2020-12-20 14:29 UTC, GadHao commented on qmoj/src/main/java/team/akina/qmoj/dto/QmojQuestionDto.java
> +    public long getId() {
我这里的插件不知道出了啥问题，没配好，感觉Lombok入侵性有点强，这里先不用Lombok了

2020-12-20 14:29 UTC, GadHao commented on qmoj/src/main/java/team/akina/qmoj/dto/QmojQuestionDto.java
> +    public List<String> getTopic_tags() {
同上

2020-12-20 14:35 UTC, GadHao commented on qmoj/src/main/java/team/akina/qmoj/dto/mapper/QmojQuestionDtoMapper.java
> +    @Mappings({@Mapping(target = "platform", expression = "java(platFormConvert(question.getPlatform()))"),
这里是一个枚举到一个平台类型字符串的转换，不写expression用不出来，考虑到MapStruct是会生成文件的，如果写错了是编译不通过的，这里还是继续使用了expression

2020-12-20 14:35 UTC, GadHao commented on qmoj/src/main/java/team/akina/qmoj/dto/mapper/QmojQuestionDtoMapper.java
> +    default String platFormConvert(byte code) {
删除了此函数

2020-12-20 14:37 UTC, GadHao commented on qmoj/src/main/java/team/akina/qmoj/dto/mapper/QmojQuestionDtoMapper.java
> +    default List<Integer> languagesConvert(String languages) {
作为在interface里的定义，这里用default比较合适，也方便写expression

2020-12-20 14:37 UTC, GadHao commented on qmoj/src/main/java/team/akina/qmoj/dto/mapper/QmojQuestionDtoMapper.java
> +    default List<String> tagsConvert(String tags) {
同上

2020-12-20 14:38 UTC, GadHao commented on qmoj/src/main/java/team/akina/qmoj/exception/DataNotFindException.java
> +public class DataNotFindException extends CustomException {
这自定义异常，没毛病！

2020-12-20 14:54 UTC, GadHao commented on qmoj/src/main/java/team/akina/qmoj/exception/ExceptionHelper.java
> +        logger.error(Arrays.toString(ex.getStackTrace()));
完整，不易读，后续调整

2020-12-20 15:03 UTC, GadHao commented on qmoj/src/test/java/team/akina/qmoj/dto/DtoConvertTest.java
> +    public Date getCurrentTime() {
这里是想获取当前时间来着，原来只用new一个就行了，写习惯DateTime.Now，以为Java没有，还百度了一圈

2020-12-20 15:04 UTC, GadHao commented on qmoj/src/main/java/team/akina/qmoj/exception/ExceptionHelper.java
> +    @ExceptionHandler(value = {DataNotFindException.class})
这样可以生效，这里注释有问题，是没有找到数据时引发的异常

2020-12-20 23:09 UTC, timeaftertime commented on qmoj/src/main/java/team/akina/qmoj/exception/DataNotFindException.java
> +public class DataNotFindException extends CustomException {
应该用体现业务含义的名字，而不是 “自定义异常”、“波波仔异常”、“GK异常”

2020-12-20 23:12 UTC, timeaftertime commented on qmoj/src/main/java/team/akina/qmoj/dto/mapper/QmojQuestionDtoMapper.java
> +    default List<Integer> languagesConvert(String languages) {
这个是单纯的转换代码，和实例无关，应该用 static 。实例方法才定义成 default ，用于给子类覆盖

2020-12-20 23:13 UTC, timeaftertime commented on qmoj/src/main/java/team/akina/qmoj/dto/mapper/QmojQuestionDtoMapper.java
> +    @Mappings({@Mapping(target = "platform", expression = "java(platFormConvert(question.getPlatform()))"),
OK，没注意到这里需要额外转换

2020-12-20 23:15 UTC, timeaftertime commented on qmoj/src/main/java/team/akina/qmoj/dto/QmojQuestionDto.java
> +    public long getId() {
波波仔已经用了Lombok，入侵行已经不是你用不用的问题了吧

2020-12-27 10:19 UTC, 21kl commented on qmoj/src/main/java/team/akina/qmoj/pojo/QmojAnswer.java
> +public class QmojAnswer {
映射前端传参可以给类加个Param或者VO更加清晰写

2020-12-27 10:23 UTC, 21kl commented on qmoj/src/main/java/team/akina/qmoj/pojo/QmojAnswer.java
> +    private int language;
我记得还有一个很重要的参数，叫做slug的，为啥这里前端不直接传过来，里扣提交用不到嘛？还是准备用id去找slug？

2020-12-27 10:27 UTC, 21kl commented on qmoj/src/test/java/team/akina/qmoj/utils/RedisTest.java
> +        answer.setTest_mode(false);
这个answer类命名似乎不太规范。。最好统一都用驼峰的形式。

2020-12-27 10:29 UTC, 21kl commented on qmoj/src/main/java/team/akina/qmoj/controller/AnswerController.java
> +@RequestMapping("/api")
api前缀按道理一般是给外部系统调用的，我理解这边只是给前端调用其实没必要用api前缀。用资源名比如answer就好

2020-12-27 11:19 UTC, GadHao commented on qmoj/src/main/java/team/akina/qmoj/pojo/QmojAnswer.java
> +public class QmojAnswer {
> 映射前端传参可以给类加个Param或者VO更加清晰写

好，现在将前端参数传入归类为Param了！

2020-12-27 11:20 UTC, GadHao commented on qmoj/src/main/java/team/akina/qmoj/pojo/QmojAnswer.java
> +    private int language;
> 我记得还有一个很重要的参数，叫做slug的，为啥这里前端不直接传过来，里扣提交用不到嘛？还是准备用id去找slug？

现在是采用了用id找slug的方式，因为考虑到可能不止是从LeetCode来的题，这里就没对LeetCode的相关参数做太特别的处理

2020-12-27 11:25 UTC, GadHao commented on qmoj/src/test/java/team/akina/qmoj/utils/RedisTest.java
> +        answer.setTest_mode(false);
> 这个answer类命名似乎不太规范。。最好统一都用驼峰的形式。

这里是根据LeetCode需要的Json生成的pojo，这类临时的pojo现在都放在pojo这个package，因为之前出现过getter，setter命名不规范影响到第三方包进行反序列化，我感觉这里保持这样吧，如果有异议欢迎继续讨论哈

2020-12-27 11:50 UTC, GadHao commented on qmoj/src/main/java/team/akina/qmoj/controller/AnswerController.java
> +@RequestMapping("/api")
> api前缀按道理一般是给外部系统调用的，我理解这边只是给前端调用其实没必要用api前缀。用资源名比如answer就好

搜了一圈，没有找到明确说关于这个的，我们这里外部要调用的话可以再加个`open`啥的，不过想了想，这里还是去掉`@RequestMapping("/api")`比较好，至少可以省代码。在下一次发布的时候会更新文档，并且告诉前端

2020-12-28 06:36 UTC, gk008 approved these changes

2020-12-28 06:38 UTC, gk008 reviewed
USER_AGENT为啥要改掉

2020-12-28 06:40 UTC, GadHao reviewed
viewed

2020-12-28 06:41 UTC, gk008 approved these changes

2020-12-28 06:41 UTC, GadHao reviewed
viewed

2020-12-28 06:42 UTC, GadHao reviewed
viewed

2020-12-28 13:27 UTC, timeaftertime approved these changes

2020-12-28 13:57 UTC, GadHao commented
@gk008 USER_AGENT改掉是那天晚上调试查询判题结果接口的时候，一直返回一个叫`PENDING`的状态字符串，获取不到结果。我以为是LeetCode识别出来爬虫了，就不停想去尽量还原浏览器行为，就完善了一下这个USER_AGENT。事实证明对我要解决的问题没什么帮助，不过想着USER_AGENT完善点肯定没啥坏处，就保留了

2020-12-28 13:58 UTC, merged